name: Go
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres16:
        image: bitnami/postgresql:16
        env:
          POSTGRESQL_PASSWORD: postgres
          POSTGRESQL_DATABASE: app
          POSTGRESQL_WAL_LEVEL: logical
        ports:
          - 5432:5432
      postgres15:
        image: bitnami/postgresql:15
        env:
          POSTGRESQL_PASSWORD: postgres
          POSTGRESQL_DATABASE: app
          POSTGRESQL_WAL_LEVEL: logical
        ports:
          - 5433:5432
      postgres14:
        image: bitnami/postgresql:15
        env:
          POSTGRESQL_PASSWORD: postgres
          POSTGRESQL_DATABASE: app
          POSTGRESQL_WAL_LEVEL: logical
        ports:
          - 5434:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: test pgsql16
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/app?replication=database&application_name=walreader1
        run: go test -v -p 1 ./...
      - name: test pgsql15
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5433/app?replication=database&application_name=walreader1
        run: go test -v -p 1 ./...
      - name: test pgsql14
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5434/app?replication=database&application_name=walreader1
        run: go test -v -p 1 ./...
